### PR TITLE
Fix markdown formatting

### PR DESCRIPTION
**Pull request by robinrodricks**
I have corrected the markdown errors and improved the description a bit. 

You can [see the result ](https://github.com/hgupta9/Alternativa3D)here.

### CODE REVIEW

**Comment by makc** [comment]
none of the images under https://github.com/hgupta9/Alternativa3D#projects-using-alternativa3d show up, tho

**Comment by makc** [comment]
...the space needs to be %20 there I think

**Comment by hgupta9** [comment]
The images are not showing in the [original version ](https://github.com/AlternativaPlatform/Alternativa3D)either. I could not make them display. I tried everything. Please accept the PR to improve the readme.

**Comment by hgupta9** [comment]
Ok, wait, I fixed it. The image URLs had spaces in them, and had to be URL encoded. Check it now.

https://github.com/hgupta9/Alternativa3D

**Comment by makc** [comment]
aww @hgupta9 you did not update the branch with the last commit

**Pull request merged**
