### PR TITLE
8.32 plus

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by makc** [comment]
@Gaspar2002 seven years too late, yes?

**Comment by ghost** [comment]
No! Alternativa3D is verry good! Please, if you have, give me the latest version of AlternativaPhysics.

**Comment by ghost** [comment]
You can see all the repositories on my page, about Alternativa3D, I want create game using Alternativa3D, AlternativaGUI and AlternativaPhysics, I created code for loading .tara-libraries and maps created with AlternativaEditor, in Alternativa 3D8.

**Comment by ghost** [comment]
Please give me AlternativaPhysics!

**Comment by makc** [comment]
I dont think it was ever open-sourced?

**Comment by ghost** [comment]
I want SWC library. It was available in AlternativaPlatform website.

**Comment by ghost** [comment]
http://web.archive.org/web/20140317194202/http://alternativaplatform.com/en/technologies/alternativaphysics/

**Comment by ghost** [comment]
"Everybody can download and use AlternativaPhysics absolutely free. However, it is necessary to place a link to alternativaplatform.com — official site of AlternativaPlatform."

**Comment by makc** [comment]
write to sergeev@alternativaplatform.com if he still works there

**Comment by ghost** [comment]
Where can I find asdoc AlternativaPhysics?

**Comment by ghost** [comment]
2.4.0 is last version of AlternativaPhysics?

**Comment by makc** [comment]
no idea, I have never used it. btw, there is [this swf](http://web.archive.org/web/20170413151105oe_/http://wiki.alternativaplatform.com/images/7/7d/AlternativaPhysics.swf) in web archive with physics code; in theory, you could probably compile your own swc with dummy a3d physics classes and replace library.swf with this in there. not sure if that would work.

**Comment by ghost** [comment]
How can I find you in social networks?

**Comment by ghost** [comment]
Do you speak Russian?

**Comment by ghost** [comment]
Do you have AlternativaGUI 5.21.0 or AlternativaEditor high version from 1.4.11?

**Comment by ghost** [comment]
I found AlternativaPhysics here http://web.archive.org/web/20130122074632if_/http://forum.alternativaplatform.com/uploads/attachments/78596=2842-BallTest.zip

**Comment by makc** [comment]
> Do you speak Russian?

нет, конечно, с чего бы человек с моим ником знал русский? совершенно необоснованное предположение.

**Comment by ghost** [comment]
Can you write a car script for AlternativaPhysics? I have a decompiled TanksTestingTool where an older version of AlternativaPhysics is used, and a car (_controller_ - Chassis - Track - SuspensionRay) is created.

**Comment by ghost** [comment]
How to weld and threshold mesh in Alternativa3D8?

**Comment by makc** [comment]
Here is BallTest.zip from above link in case it expires:
[BallTest.zip](https://github.com/AlternativaPlatform/Alternativa3D/files/1773096/BallTest.zip)

**Pull request closed without merging**
